name: 'Renew Hax'

on:
  workflow_dispatch:
  schedule:
    - cron: '19 17 */5 * *'
jobs:
  hax_renew:
    runs-on: windows-2022
    
    steps:
      - name: 'Renewing Hax VPS ....'
        shell: cmd
        env:
          SECRET_USERNAME: ${{ secrets.USERNAME }}
          SECRET_PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          curl -sSL -O https://github.com/SeanSuny/Hax_extend/raw/main/HaxAutoReNew.exe
          HaxAutoReNew.exe -user "%SECRET_USERNAME%" -password "%SECRET_PASSWORD%"
